name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v4
        name: Set up JDK 11
        with:
          distribution: "temurin"
          java-version: 11
          cache: gradle
      - name: gradle check
        run: ./gradlew check jacocoTestReport
      - name: Save test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: test-result
          path: build/reports/tests/test
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html
